// Generated by dts-bundle v0.3.0

declare module 'classnamer' {
    export interface ClassNameFragment {
        [key: string]: boolean;
    }
    export function format(...args: Array<string | number | ClassNameFragment>): string;
}

