// Generated by dts-bundle v0.3.0

declare module 'classnamer' {
    export type ClassNamePrimitive = string | number | boolean;
    export type ClassNameObject = {
        [key: string]: boolean;
    };
    export type ClassNameFragment = ClassNamePrimitive | ClassNameObject | ClassNameFragmentList;
    export interface ClassNameFragmentList extends Array<ClassNameFragment> {
    }
    export function format(...args: ClassNameFragment[]): string;
}

